In [8]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

LOAD CSV FILE INTO A DATAFRAME

In [9]:
df= pd.read_csv(r"c:\Users\hp\Desktop\Sirbright\apartment_data1.csv")
df.head()

,Apartment_ID,Location,Postal Code,Number of Floors,Number of Rooms,Ceiling Finish,Room Size (sq. meters),Year Built,Month Built,Utilities Available,Price of Apartment,Price of Apartment (USD)
0,NRAS0001,NorthEast_Ekiti State_437 Broadway Road,995056.0,12.0,8.0,Gypsum,48.130072,1993.0,11.0,"Gas, Solar Power, Water Supply, Internet",26691090.0,35588.120000
1,NRAS0002,NorthWest_Plateau State_387 Main Street,568247.0,1.0,6.0,POP,29.288397,2007.0,1.0,Solar Power,18158672.0,24211.562667
2,NRAS0003,SouthEast_Nasarawa State_247 Unity Avenue,304911.0,6.0,7.0,POP,13.122074,2006.0,10.0,"Internet, Solar Power, Electricity, Gas",6058081.0,8077.441333
3,NRAS0004,SouthEast_Bauchi State_323 Broadway Road,938476.0,6.0,10.0,Wood,24.854701,1952.0,11.0,"Solar Power, Gas, Electricity, Water Supply",49056996.0,65409.328000
4,NRAS0005,NorthWest_Plateau State_493 Unity Avenue,213401.0,7.0,1.0,Wood,39.275249,2006.0,5.0,"Water Supply, Internet",31548382.0,42064.509333

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Apartment_ID              10000 non-null  object
 1   Location                  9985 non-null   object
 2   Postal Code               9991 non-null   float64
 3   Number of Floors          9990 non-null   float64
 4   Number of Rooms           9987 non-null   float64
 5   Ceiling Finish            9982 non-null   object
 6   Room Size (sq. meters)    9986 non-null   float64
 7   Year Built                9983 non-null   float64
 8   Month Built               9987 non-null   float64
 9   Utilities Available       9991 non-null   object
 10  Price of Apartment        9987 non-null   float64
 11  Price of Apartment (USD)  9987 non-null   float64
dtypes: float64(8), object(4)
memory usage: 937.6+ KB

In [11]:
df["Year Built"] = df["Year Built"].astype("string").str.replace(".0", "")

In [12]:
x = ["Year Built", "Month Built"]
for i in x:
    df[f"{i}"] = df[f"{i}"].astype("string").str.replace(".0", "")

In [13]:
df.head()

,Apartment_ID,Location,Postal Code,Number of Floors,Number of Rooms,Ceiling Finish,Room Size (sq. meters),Year Built,Month Built,Utilities Available,Price of Apartment,Price of Apartment (USD)
0,NRAS0001,NorthEast_Ekiti State_437 Broadway Road,995056.0,12.0,8.0,Gypsum,48.130072,1993,11,"Gas, Solar Power, Water Supply, Internet",26691090.0,35588.120000
1,NRAS0002,NorthWest_Plateau State_387 Main Street,568247.0,1.0,6.0,POP,29.288397,2007,1,Solar Power,18158672.0,24211.562667
2,NRAS0003,SouthEast_Nasarawa State_247 Unity Avenue,304911.0,6.0,7.0,POP,13.122074,2006,10,"Internet, Solar Power, Electricity, Gas",6058081.0,8077.441333
3,NRAS0004,SouthEast_Bauchi State_323 Broadway Road,938476.0,6.0,10.0,Wood,24.854701,1952,11,"Solar Power, Gas, Electricity, Water Supply",49056996.0,65409.328000
4,NRAS0005,NorthWest_Plateau State_493 Unity Avenue,213401.0,7.0,1.0,Wood,39.275249,2006,5,"Water Supply, Internet",31548382.0,42064.509333

In [14]:
df["Price of Apartment"] = df["Price of Apartment"].astype("string").str.replace(".0", "")

In [15]:
df.head()

,Apartment_ID,Location,Postal Code,Number of Floors,Number of Rooms,Ceiling Finish,Room Size (sq. meters),Year Built,Month Built,Utilities Available,Price of Apartment,Price of Apartment (USD)
0,NRAS0001,NorthEast_Ekiti State_437 Broadway Road,995056.0,12.0,8.0,Gypsum,48.130072,1993,11,"Gas, Solar Power, Water Supply, Internet",26691090,35588.120000
1,NRAS0002,NorthWest_Plateau State_387 Main Street,568247.0,1.0,6.0,POP,29.288397,2007,1,Solar Power,18158672,24211.562667
2,NRAS0003,SouthEast_Nasarawa State_247 Unity Avenue,304911.0,6.0,7.0,POP,13.122074,2006,10,"Internet, Solar Power, Electricity, Gas",6058081,8077.441333
3,NRAS0004,SouthEast_Bauchi State_323 Broadway Road,938476.0,6.0,10.0,Wood,24.854701,1952,11,"Solar Power, Gas, Electricity, Water Supply",49056996,65409.328000
4,NRAS0005,NorthWest_Plateau State_493 Unity Avenue,213401.0,7.0,1.0,Wood,39.275249,2006,5,"Water Supply, Internet",31548382,42064.509333

In [16]:
df["Date Built"] = df["Year Built"] + "-" + df["Month Built"]
df.head()

,Apartment_ID,Location,Postal Code,Number of Floors,Number of Rooms,Ceiling Finish,Room Size (sq. meters),Year Built,Month Built,Utilities Available,Price of Apartment,Price of Apartment (USD),Date Built
0,NRAS0001,NorthEast_Ekiti State_437 Broadway Road,995056.0,12.0,8.0,Gypsum,48.130072,1993,11,"Gas, Solar Power, Water Supply, Internet",26691090,35588.120000,1993-11
1,NRAS0002,NorthWest_Plateau State_387 Main Street,568247.0,1.0,6.0,POP,29.288397,2007,1,Solar Power,18158672,24211.562667,2007-1
2,NRAS0003,SouthEast_Nasarawa State_247 Unity Avenue,304911.0,6.0,7.0,POP,13.122074,2006,10,"Internet, Solar Power, Electricity, Gas",6058081,8077.441333,2006-10
3,NRAS0004,SouthEast_Bauchi State_323 Broadway Road,938476.0,6.0,10.0,Wood,24.854701,1952,11,"Solar Power, Gas, Electricity, Water Supply",49056996,65409.328000,1952-11
4,NRAS0005,NorthWest_Plateau State_493 Unity Avenue,213401.0,7.0,1.0,Wood,39.275249,2006,5,"Water Supply, Internet",31548382,42064.509333,2006-5

In [17]:
df.drop(columns= x, inplace= True)
df.head()

,Apartment_ID,Location,Postal Code,Number of Floors,Number of Rooms,Ceiling Finish,Room Size (sq. meters),Utilities Available,Price of Apartment,Price of Apartment (USD),Date Built
0,NRAS0001,NorthEast_Ekiti State_437 Broadway Road,995056.0,12.0,8.0,Gypsum,48.130072,"Gas, Solar Power, Water Supply, Internet",26691090,35588.120000,1993-11
1,NRAS0002,NorthWest_Plateau State_387 Main Street,568247.0,1.0,6.0,POP,29.288397,Solar Power,18158672,24211.562667,2007-1
2,NRAS0003,SouthEast_Nasarawa State_247 Unity Avenue,304911.0,6.0,7.0,POP,13.122074,"Internet, Solar Power, Electricity, Gas",6058081,8077.441333,2006-10
3,NRAS0004,SouthEast_Bauchi State_323 Broadway Road,938476.0,6.0,10.0,Wood,24.854701,"Solar Power, Gas, Electricity, Water Supply",49056996,65409.328000,1952-11
4,NRAS0005,NorthWest_Plateau State_493 Unity Avenue,213401.0,7.0,1.0,Wood,39.275249,"Water Supply, Internet",31548382,42064.509333,2006-5

In [18]:
df["Location"].str.split("_")

0         [NorthEast, Ekiti State, 437 Broadway Road]
1         [NorthWest, Plateau State, 387 Main Street]
2       [SouthEast, Nasarawa State, 247 Unity Avenue]
3        [SouthEast, Bauchi State, 323 Broadway Road]
4        [NorthWest, Plateau State, 493 Unity Avenue]
                            ...
9995    [NorthCentral, Enugu State, 312 Unity Avenue]
9996         [NorthWest, Kebbi State, 56 Main Street]
9997        [NorthWest, Kano State, 435 Unity Avenue]
9998       [NorthEast, Ondo State, 450 Broadway Road]
9999          [NorthWest, Benue State, 51 SDA Street]
Name: Location, Length: 10000, dtype: object

In [ ]:
df["Geopolitical Zone"], df["State"]